server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,beans
info:
  application:
    name: Spring Sample Application
    description: This is my first spring boot application
    version: 1.0.0
logging:
  register-shutdown-hook: true
  level:
    web: DEBUG
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
  #     log-condition-evaluation-delta: true
---
spring:
  config:
    activate:
      on-profile:  qa
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
