server:
  port: 8080
  # SSL
  # port: 8443
  ssl:
    enabled: false
    key-store: ${CERT_PATH}/cert.p12
    key-store-password: password
    keyStoreType: PKCS12
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info,beans
logging:
  register-shutdown-hook: true
  level:
    web: DEBUG
    root: INFO
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
